### ISSUE TITLE
Overall code cleanup

### ISSUE THREAD

**Issue by delivey** [AmreshSinha/Spotify-Cards-API#10]
The codebase is pretty messy right now, this issue suggests what to fix to change that.

1. Remove unused imports like this:
```js
const fetch = require('cross-fetch') // Not Used
const path = require("path")
const express = require('express')
const bodyParser = require('body-parser') // Not Used
const url = require('url') // Not Used
const querystring = require('querystring') // Not Used
const fs = require('fs') // Not Used
const SpotifyWebApi = require('spotify-web-api-node')
const cors = require('cors');
```
2. Remove unused vars, for example:
```js
let songName, songArtist, songImageURL; // Not Used
```
3. Use await for the `newToken` function instead of the current then method:
4. Use awaits instead of thens in the `searchTracksByName` and `searchTracksById` functions
5. Use a `join` instead of this:
```js
    for (let i = 0; i < artistList.length; i++) {
        if (i==artistList.length-1) {
            artistString += artistList[i]
        }
        else {
            artistString += artistList[i] + ", "
        }
    }
```
6. Merge the `searchTracksByName` and `searchTracksById` functions. I suggest to provide the function with a string called `searchType` using which the function decides whether to call the spotify API for song data like in the `searchTracksByName` function or like in the `searchTracksById` function.
7. Remove unused comments, for example: 
```js
            // const spotifyCard = {
            //     spotifyCardURL: cardURL
            // }
            // res.render('api', spotifyCard)
            // res.send(cardURL)
            // res.write('<img src = "'+cardURL+'">');
            // console.log(cardURL) // Image which we want
            // fs.writeFileSync('./test.png', buffer)
```

These are all of my suggestions for now, I can do all of them, let me know if I should do this and which ones.

**Comment by AmreshSinha** [comment]
yeah you can go with
1st, 5th, 7th. Others I want for further development. :+1:
