### ISSUE TITLE
Even if `color=000` is used in the api request, black color is not being used.

### ISSUE THREAD

**Issue by letsintegreat** [AmreshSinha/Spotify-Cards-API#15]
### Version

v16.13.1

### What steps will reproduce the bug?

`/api?name=Silver%20Lining&color=000`

This request should get black background color, but that's not the case.

![](https://i.imgur.com/OugcbF0.png)

### How often does it reproduce? Is there a required condition?

Every time 000 is used for hex, if one uses 000000, it works fine.

### Additional information

    let imageColor = '#000';

Instead of using `#000` as a flag to determine if the user has specified the value of color, a boolean variable should be used.

**Comment by letsintegreat** [comment]
Apart from this, we can also support hex codes with # at the start, because many hex code websites make the user copy the code with #. So we can just support both the hex codes with and without #.

And, if the entered color is not a valid hex code (6 letters, or 3 letters, each from [0-9a-fA-F], with or without a leading #), we could show an error instead of showing a random color.

If the color property is not mentioned in the API request, the average color is used automatically, this feature is very handy. However, this behavior is not stated in the [docs](https://spotify-cards.up.railway.app/). I think it should be mentioned in the docs so that users could make use of this.

**Comment by letsintegreat** [comment]
Tasks to be done:

- [ ] Remove the use `#000` as a flag.
- [ ] Add support for hex code with `#` too.
- [ ] Remove the line from docs that asks to use hex code without #.
- [ ] Show a message if the given hex code is not valid.
- [ ] Update docs to add information about automatically using the best-suited color according to the image, if the `color` property is not in the request.

**Comment by AmreshSinha** [comment]
> Apart from this, we can also support hex codes with # at the start, because many hex code websites make the user copy the code with #. So we can just support both the hex codes with and without #.
> 
> And, if the entered color is not a valid hex code (6 letters, or 3 letters, each from [0-9a-fA-F], with or without a leading #), we could show an error instead of showing a random color.

Yep :+1: 

> If the color property is not mentioned in the API request, the average color is used automatically, this feature is very handy. However, this behavior is not stated in the [docs](https://spotify-cards.up.railway.app/). I think it should be mentioned in the docs so that users could make use of this.

Thanks for pointing out! :+1:

<hr>

> Tasks to be done:
> 
> * [ ]  Remove the use `#000` as a flag.
> * [ ]  Add support for hex code with `#` too.
> * [ ]  Remove the line from docs that asks to use hex code without #.
> * [ ]  Show a message if the given hex code is not valid.
> * [ ]  Update docs to add information about automatically using the best-suited color according to the image, if the `color` property is not in the request.

Seems fine to me! :+1: You can start working in it! :blush: :+1:
