### ISSUE TITLE
Text not visible when background is white.

### ISSUE THREAD

**Issue by letsintegreat** [AmreshSinha/Spotify-Cards-API#19]
Text is not visible when the chosen background color is similar to white, as here:

![image](https://user-images.githubusercontent.com/37345795/147587570-fa89c231-0bb9-4608-97ed-423343b42edc.png)

I think the text color should be changed depending on the background color.
[This answer](https://stackoverflow.com/a/52453462/9134576) can be super useful.

![](https://i.stack.imgur.com/OXrne.png)

IMO, text color should be changed when `delta E <= 2`.
Right now, I am thinking of using the average color of img as the text color, in case the background color is similar to white.

But if the average color is also similar to the background color, I haven't figured that out. WDYT?

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by AmreshSinha** [comment]
Yeah I had this problem too. 
You can work on this :+1:
