### ISSUE TITLE
Adding create card button option for user. 

### ISSUE THREAD

**Issue by sauravrajleaf** [AmreshSinha/Spotify-Cards-API#20]
**Is your feature request related to a problem? Please describe.**
Currently, there is no input or create card button option in the page. User has to copy the API link and hit the end points after entering the data in the url to get the result. 

**Describe the solution you'd like** 
A feature can be implemented for the user. So that the user can type the song name and color code as desired and the result will be show on the same or new page. Similarly, for other option like for song id the input can be changed depending on the option chosen by the user. This will result in more user friendly UI. 
Just a simple representation of the proposed feature.
![screenshot-127 0 0 1_5500-2021 12 29-05_18_51(1)](https://user-images.githubusercontent.com/52833031/147615362-a27f0b6b-8683-49f3-ab18-03ade2a98730.png)

**Describe alternatives you've considered**
No alternatives right now.

**Comment by sauravrajleaf** [comment]
If this feature is can be implemented. Please assign this to me.

**Comment by AmreshSinha** [comment]
Seems cool to me.
Here's what you can do:
- Styling (Custom CSS)
- On Create Card it should change the default image above "Unofficial Spotify Promo Cards API" headline

**Comment by sauravrajleaf** [comment]
Okay, got it. I will do the changes in my separate branch XD. 

- Just to be sure, by Custom CSS you mean the same CSS format that has been used in the index.html file. Right? 

- And for click event we will also have to include Js. So should I go with inline scirpt file or I should use external Js file for handling that event?

**Comment by AmreshSinha** [comment]
> * Just to be sure, by Custom CSS you mean the same CSS format that has been used in the index.html file. Right?

By it I meant don't use any predefined CSS library like tailwind. Tho you can use bootstrap as its also used for other theming :+1: 

> * And for click event we will also have to include Js. So should I go with inline scirpt file or I should use external Js file for handling that event?

any of the option is fine :+1: :blush:

**Comment by sauravrajleaf** [comment]
okay. Thanks for the information :+1:

**Comment by sauravrajleaf** [comment]
As of now the page layout is completely changed. Can you please tell on which page or place should I try adding this feature.

**Comment by AmreshSinha** [comment]
Sorry but now I guess adding it on this new UI will look good 😕.

Will check again and let you know!

**Comment by letsintegreat** [comment]
@sauravrajleaf @AmreshSinha I think this issue can be scaled up now:

A new section can be added to docs' home page (alongside Intro, Usage, and Github) called "Play with the API".

And in that section, you can take input for all the different possible parameters. Once submitted, the API link and the corresponding card will be rendered next to it.

@sauravrajleaf if you are want to work on this, great!
Else I am willing to take up this issue. (Provided Amresh bhaiya wants this feature to be added.)

**Comment by AmreshSinha** [comment]
Seems fine to me!
