### ISSUE TITLE
Removal of brackets from song name.

### ISSUE THREAD

**Issue by letsintegreat** [AmreshSinha/Spotify-Cards-API#23]
All the songs' names I have come across on Spotify use brackets to add their artist's name.
I think we should remove the bracketed text from the song name before displaying it on the card because it is just noise as we have artists' names in another field anyways.

Removing the bracketed text will make the card more minimal and less congested.

![image](https://user-images.githubusercontent.com/37345795/147807760-06f64f38-0a44-41e7-aab5-683bf99990c1.png)

![image](https://user-images.githubusercontent.com/37345795/147809042-88289353-1933-476e-8739-9a2f0825a157.png)

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by AmreshSinha** [comment]
The actual Spotify site's card includes the bracketed stuff too so I don't think incorporating it will be good :thinking: 
![image](https://user-images.githubusercontent.com/35039730/147824217-567e4f9d-4d58-4418-85bf-efbd8767314b.png)

**Comment by letsintegreat** [comment]
@AmreshSinha Oh, I didn't check their card, just saw this "Oh My Gawd" card on their [landing page](https://promocards.byspotify.com/), and I thought they were also removing it because that song name has bracketed text.
![image](https://user-images.githubusercontent.com/37345795/147824519-dd0a7052-90a4-47c7-bc0f-f677552b92c2.png)

But yeah, they are not removing it while making the card, just checked.
Closing this issue.
