### ISSUE TITLE
Landscape image not showing up. 

### ISSUE THREAD

**Issue by sauravrajleaf** [AmreshSinha/Spotify-Cards-API#26]
### Version

v17.3.0

### Platform

OS: Garuda Linux

### What steps will reproduce the bug?

- Start the server in localhost & open docs-page.html in live server. 
- You'll see the landscape image is not getting fetched. It looks like as shown in the given picture
![screenshot-127 0 0 1_5500-2022 01 02-05_35_35](https://user-images.githubusercontent.com/52833031/147862820-bf37c6b7-54ea-438a-bf1c-dd6baf1fe903.png)
.

### How often does it reproduce? Is there a required condition?

It happens whenever the site is opened in localhost. 

### Is there any Package conflicting with other packages?

No. As per my knowledge there is no issue for package conflicting. 

### What is the expected behavior?

The landscape image should show up just like the square image. 

### What do you see instead?

Provided in the screenshot above.

**Comment by AmreshSinha** [comment]
its working this side :thinking:
