### ISSUE TITLE
Theme Color Extraction

### ISSUE THREAD

**Issue by AmreshSinha** [AmreshSinha/Spotify-Cards-API#3]
**Is your feature request related to a problem? Please describe.**
By default the color for the background is black. So, if in the request, color is not provided the client will get an image with Black background.

**Describe the solution you'd like**
Instead of Black Color, we can extract the Dominant or Average color from the image and can set the background for that Song Card with that color code.

**Describe alternatives you've considered**
You can either code your own script for this or use already available packages like Vibrant.

**Comment by delivey** [comment]
Hey, can you assign me this issue? I can do this.

**Comment by AmreshSinha** [comment]
Sure :+1: 
I have assigned you :heavy_check_mark:

**Comment by delivey** [comment]
Hey, I've pretty much completed the task, doing some cleaning up. One pretty big inconvienience I noticed is that I have to change / add code in two functions so it would work for both requests by id and by name. Can I open an issue for this? Could fix this myself then as well.

**Comment by AmreshSinha** [comment]
Yeah, I actually created 2 functions at the start. Right now you can create a PR with edits in both.
In the future, I will edit and make one function instead of those 2. I still have to do some work regarding text wrap, playlist, podcast, etc other URIs. That's why I have created separate functions for them.

**Comment by AmreshSinha** [comment]
Altho you can share your ideas as a code block here itself in this issue as well too :blush:

**Comment by delivey** [comment]
What other idea are you reffering to?

**Comment by AmreshSinha** [comment]
@delivey 

> One pretty big inconvienience I noticed is that I have to change / add code in two functions so it would work for both requests by id and by name. Can I open an issue for this? Could fix this myself then as well.

**Comment by delivey** [comment]
Well sharing the code for merging the functions in a code block in this issue would not be optimal. I'm not sure we're on the same page here. Let me know if later on you want to save time and let me create the PR for merging the functions.

Will open a PR for this issue (Theme Color Extraction) in a few minutes.

On another note, is it just me or does the image sometimes contain the album name instead of the actual song name?

**Comment by AmreshSinha** [comment]
> Well sharing the code for merging the functions in a code block in this issue would not be optimal. I'm not sure we're on the same page here. Let me know if later on you want to save time and let me create the PR for merging the functions.
> 
> 
> 
> Will open a PR for this issue (Theme Color Extraction) in a few minutes.
> 
> 
> 
> On another note, is it just me or does the image sometimes contain the album name instead of the actual song name?
> 
> 

Ex.
Album Name: Somewhere New
Song Name: Your Spell
Link to song: https://open.spotify.com/track/1y6ZCzDYOkXXq5o7BUkbIi?si=EO-UPiaJQUuYbn1PTsjVCw&dl_branch=1

Spotify Card:

![Example](https://spotify-cards.up.railway.app/api?id= 1y6ZCzDYOkXXq5o7BUkbIi)

**Comment by AmreshSinha** [comment]
> Well sharing the code for merging the functions in a code block in this issue would not be optimal. I'm not sure we're on the same page here. Let me know if later on you want to save time and let me create the PR for merging the functions.
> 
> Will open a PR for this issue (Theme Color Extraction) in a few minutes.
> 
> On another note, is it just me or does the image sometimes contain the album name instead of the actual song name?


Album Name: Somewhere New
Link to Album:  https://open.spotify.com/album/2tYcFWd25g2Y69VQHiNJwD?si=kpz0IFRgQtqpKUDSKDXTew&dl_branch=1

Song Name: Your Spell
Link to Song: https://open.spotify.com/track/1y6ZCzDYOkXXq5o7BUkbIi?si=a1f1311e917542d9
ID: 1y6ZCzDYOkXXq5o7BUkbIi

Spotify Card for that image: 

![Have to Fix](https://spotify-cards.up.railway.app/api?id=1y6ZCzDYOkXXq5o7BUkbIi&color=A0C3D2)

@delivey thanks for pointing it out. I will open an issue for it. If you wanna work on that too you are welcome 👍

**Comment by delivey** [comment]
Can you test and merge the PR for this issue? I submitted it.
