### ISSUE TITLE
Text Wrap

### ISSUE THREAD

**Issue by AmreshSinha** [AmreshSinha/Spotify-Cards-API#4]
**Is your feature request related to a problem? Please describe.**
Currently, if a song has a big name then it's full name crosses the canvas instead of wrapping into new line

**Describe the solution you'd like**
Implementing Text Wrap with which longer names can automatically wrap into next line and also the font size of the name should decrease dynamically.

This might help: http://jsfiddle.net/mg9jxhbn/1/

* Font size should decrease dynamically too
* Space between "S O N G" and song name, and song name and the artist name should decrease too
* This wrapping is also needed for artists name section too

**Describe alternatives you've considered**
No Alternatives right now.

**Comment by realhunter7869** [comment]
Hey @AmreshSinha, I would like to work on this issue. Can you add the tag for Hacktoberfest?

**Comment by realhunter7869** [comment]
My solution is to use songname.lastIndexOf("{space}", max_length).... Where by estimates the max length of text can go upto 10... If this condition is found we can have a flag and if the flag is found then we can do some change to the text output by reducing the font px and moving the string from max_length+1 to the next line....

**Comment by AmreshSinha** [comment]
> Hey @AmreshSinha, I would like to work on this issue. Can you add the tag for Hacktoberfest?

Yeah the tag is added to the repository

> My solution is to use songname.lastIndexOf("{space}", max_length).... Where by estimates the max length of text can go upto 10... If this condition is found we can have a flag and if the flag is found then we can do some change to the text output by reducing the font px and moving the string from max_length+1 to the next line....

Yeah :+1: This way looks fine to me. Can you share a code snippet (jsfiddle) showing the implementation of this on a small size canvas?

**Comment by letsintegreat** [comment]
I'd like to work on this issue.
