### ISSUE TITLE
Add CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by AmreshSinha** [AmreshSinha/Spotify-Cards-API#56]
**Is your feature request related to a problem? Please describe.**
Currently, there are no CONTRIBUTING guidelines for newcomers.

**Describe the solution you'd like**
Add a `CONTRIBUTING.md` file listing all the rules and guidelines which should be followed while contributing to the repo.

**Anything extra you want to add?**
Make sure it at least follows the general rules of creating a new branch and how to name PRs. 

**References**
You are free to see any references and examples. Just don't copy them straightforwardly.
Some examples:
https://github.com/AmreshSinha/sshot/blob/main/CONTRIBUTING.md
https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md
https://reactjs.org/docs/how-to-contribute.html
https://github.com/vercel/next.js/blob/canary/contributing.md

**Comment by depimomo** [comment]
Hello! May I contribute to this issue? Do you have anything specific in mind to put on the `CONTRIBUTING.md` file?

**Comment by AmreshSinha** [comment]
Assigned 👍

**Comment by depimomo** [comment]
okay, working on it. Thank you!
