### ISSUE TITLE
Add Docker steps in HOSTING.md

### ISSUE THREAD

**Issue by AmreshSinha** [AmreshSinha/Spotify-Cards-API#57]
**Is your feature request related to a problem? Please describe.**
The `HOSTING.md` does not have steps for hosting with docker under the host on your own server section.

**Describe the solution you'd like**
Add steps for hosting with docker and reverse proxying it with Traefik. Make sure you add a reference to installing Traefik, which can be found here: https://fossian.com/simplify-deployment-traefik-walk-through/ .

Make sure you verify the steps by trying it on an actual virtual server and attaching a subdomain or domain to it.
You can get a virtual server for free on the oracle cloud free tier or digitalocean trial.
And for a subdomain, you can get one for free on [afraid DNS](https://freedns.afraid.org/) or any other provider.

You can also add images for the steps.

**Comment by AmreshSinha** [comment]
Sure just make sure you test out everything. Also if possible add images in the steps too.

**Comment by aswinikalyan30** [comment]
Could you please assign it to someone else?

**Comment by Purvarth** [comment]
Can I work on this?
