### ISSUE TITLE
[BUG] Picking Album Name instead of Song Name

### ISSUE THREAD

**Issue by AmreshSinha** [AmreshSinha/Spotify-Cards-API#6]
### What steps will reproduce the bug?

> Well sharing the code for merging the functions in a code block in this issue would not be optimal. I'm not sure we're on the same page here. Let me know if later on you want to save time and let me create the PR for merging the functions.
> 
> Will open a PR for this issue (Theme Color Extraction) in a few minutes.
> 
> On another note, is it just me or does the image sometimes contain the album name instead of the actual song name?

Album Name: Somewhere New
Link to Album:  https://open.spotify.com/album/2tYcFWd25g2Y69VQHiNJwD?si=kpz0IFRgQtqpKUDSKDXTew&dl_branch=1

Song Name: Your Spell
Link to Song: https://open.spotify.com/track/1y6ZCzDYOkXXq5o7BUkbIi?si=a1f1311e917542d9
ID: 1y6ZCzDYOkXXq5o7BUkbIi

Spotify Card for that image: 

![Have to Fix](https://spotify-cards.up.railway.app/api?id=1y6ZCzDYOkXXq5o7BUkbIi&color=A0C3D2)

@delivey thanks for pointing it out. I will open an issue for it. If you wanna work on that too you are welcome 👍

_Originally posted by @AmreshSinha in https://github.com/AmreshSinha/Spotify-Cards-API/issues/3#issuecomment-932681111_

### How often does it reproduce? Is there a required condition?

<--BUG-->

### Is there any Package conflicting with other packages?

<--NO-->

### What is the expected behavior?

It should have shown the song name instead of the parent album's name.

### What do you see instead?

A card with its parent album's name.

### Additional information

For info, you can test it out yourself by using the reproducing step.
Also,
<a href="https://github.com/AmreshSinha/Spotify-Cards-API/issues/3">Issue #3</a>

**Comment by delivey** [comment]
Hey, can you assign me to this issue? Should be pretty easy.

**Comment by AmreshSinha** [comment]
Assigned You ✔️
