### ISSUE TITLE
Improve accuracy for searching by name.

### ISSUE THREAD

**Issue by delivey** [AmreshSinha/Spotify-Cards-API#8]
(Discussion needed first)

When searching by name, the 6th result of the search will be omitted due to this line:
`await spotifyApi.searchTracks(name, {market:'US', limit:1, offset:5})`
In my opinion, we should remove the offset and show the 1st result instead. This will result in the most popular song being omitted which statistically speaking should be what the user was searching for.

Examples: 
**Query**: the%20nights (the nights)
**Offset 5**: 
![image](https://user-images.githubusercontent.com/35540227/135705650-daabf15c-50e7-4c5c-a1f1-e4f4822b34ba.png)
**No offset**: 
![image](https://user-images.githubusercontent.com/35540227/135705671-144375ba-171b-4a3b-8b78-53667dd3b5e8.png)

Very simple issue to fix, literally just removing a few characters from the line mentioned above in `/index.js`

**Comment by AmreshSinha** [comment]
I don't know why I kept offset 5 at the start 😕. Maybe I thought of what if the several song with same name are there.
Anyways, I think setting offset to 1 will be fine. As if the user doesn't find his song then he can always use the id param.

You can go ahead. I have assigned you.
